"""
Reports Page - Browse and view generated reports.

This page provides an interface for viewing reports generated by the ZeroClaw gateway.
"""

import streamlit as st
from components.reports import render_reports_listing


def render():
    """
    Render the Reports page.

    Displays the reports listing interface which includes:
    - Search functionality
    - Report grid/list
    - Report viewer dialog
    - Export capabilities
    """
    render_reports_listing()


# Public API
__all__ = ['render']
